version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - 5555:5432
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

  backend:
    image: node:12
    volumes:
      - ./backend:/app
    working_dir: /app
    environment:
      - PGPASSWORD=postgrespassword
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPORT=5432
    command: node_modules/.bin/persea dev
    ports:
      - 8080
    labels:
      - "traefik.http.middlewares.strip-api.stripprefix.prefixes=/api"
      - "traefik.http.routers.backend.priority=200"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.backend.middlewares=strip-api"

  frontend:
    image: node:12
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: yarn dev
    ports:
      - 3000
    labels:
      - "traefik.http.routers.frontend.priority=100"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"

  router:
    image: traefik:v2.2
    command: --api.insecure=true --providers.docker
    ports:
      - 1113:80
      - 1114:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


volumes:
  db_data:
